### PR TITLE
Cleanup at batch exit (if used from command-line leaves current state intact)

### PR DESCRIPTION
**Pull request by birbilis**

### CODE REVIEW

**Review by alexgand — APPROVED** [review]
Merged, thanks!

**Comment by alexgand** [comment]
Also, do you want to edit README.MD for instructions on how to use `run_VirtualEnv.bat` ? Thanks!

**Comment by birbilis** [comment]
will see to it

**Comment by birbilis** [comment]
done - https://github.com/alexgand/springer_free_books/pull/61

**Pull request merged**
