### PR TITLE
Updated readme with info on batch file

### PR DESCRIPTION
**Pull request by birbilis**
- added notes how to run the batch file (auto-detection of python version etc.)
- added notes on how to get python for windows users

### CODE REVIEW

**Comment by alexgand** [comment]
Great, I merged the PR #57 which also modified README.MD. Can you submit the changes again, with the new README.MD? Thanks.

**Comment by birbilis** [comment]
try again now

**Review by alexgand — CHANGES_REQUESTED** [review]
Modified the README.MD again and can't merge your PR! Please fix it and I'll merge it ASAP. Thanks

**Comment by alexgand** [comment]
I updated the README.MD with the instructions, thanks!

**Pull request closed without merging**
