### PR TITLE
issue #19 - check for corrupted/invalid files

### PR DESCRIPTION
**Pull request by pjungermann**
- check whether PDFs are valid using PyPDF2
- check whether ePubs (=Zips) are valid using zipfile
- try 3 times and then give up and continue
    - print error information
    - can be recovered/tried again by running the downloader again

### CODE REVIEW

**Comment by pjungermann** [comment]
caveat: those additional checks will make the downloader slower

**Comment by martinbra** [comment]
Hey   @pjungermann, very nice idea of yours. 
There could be an option like "python main.py --validate-at-end" to validate files after all the downloads are completed, in order to not make the downloader slower.

**Comment by pjungermann** [comment]
@martinbra yes, this could be done. It would not be so easy to retry then, but as this script is able to cover this with a re-run, might be alright.

Not sure if @alexgand wants any of those options merged though.

**Comment by alexgand** [comment]
Folks, for the sake of simplicity I'll leave the code as it is. Thanks, though.

**Pull request closed without merging**
