### PR TITLE
Adds a progress bar for the download of individual books

### PR DESCRIPTION
**Pull request by wildmichael**
The progress bars for the books are kept as a log and the overall progress is now labelled as such.

### CODE REVIEW

**Comment by alexgand** [comment]
Hi, with the last merge this PR is showing conflict in `helper.py`.
Can you fix it so I can merge it?
Thanks.

**Comment by wildmichael** [comment]
Done, thanks for the quick feedback.

**Review by alexgand — APPROVED** [review]
Merged, thanks!

**Comment by alexgand** [comment]
Great work, by the way, I really liked it!

**Comment by wildmichael** [comment]
Thanks!

**Pull request merged**
