### PR TITLE
Added code to limit the maximum filename length

### PR DESCRIPTION
**Pull request by chaosAD**
A filename cannot exceed a certain maximum length. Error will be thrown if it is breached. The max length imposed by the OS is computed from the full path of the file. This means, the maximum length for a bookname changes according to which directory it is stored. In the script, the limit is set to either 145 or the max length determined on-the-fly, whichever is smaller. This will solve #72.

### CODE REVIEW

**Review by alexgand — APPROVED** [review]
Merged, thanks!

**Comment by alexgand** [comment]
I had to revert this PR, on my windows machine it stoped working.

**Comment by chaosAD** [comment]
Can you elaborate further because it works fine on my machine?

**Comment by alexgand** [comment]
image

**Comment by chaosAD** [comment]
Oh! ok. Can you try this [commit](https://github.com/chaosAD/springer_free_books/tree/a1a1cdcc59d1cdc8d7b42696d7f8879618c052b5)? Hopefully, I have fixed it.

**Comment by alexgand** [comment]
Tried, another error:
image

**Comment by chaosAD** [comment]
Fixed those problems in my [latest commit](https://github.com/chaosAD/springer_free_books/).

**Comment by alexgand** [comment]
Still don't work here:
image

**Comment by chaosAD** [comment]
Okay. I fixed once and for all and tested those functions on Python 3.8.1; finally. Sorry. for the trouble. 

I have pushed the new commit to my repository. Can you try it once more?

**Comment by alexgand** [comment]
Now it works!

**Comment by chaosAD** [comment]
Hi Alex,

Actually there is one pending PR by ghost. He somehow did a pull request on my behalf for some reason I am not sure. So now I can't create any further pull requests because of that. Could you please either accept that pull request or dismiss it?

Thanks.

rgds,
chaosAD

________________________________

**Comment by alexgand** [comment]
Thanks @chaosAD, I approved and merged the PR.

**Pull request merged**
